# See https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
# and https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: Bug report
description: Unexpected behaviour
labels: ["refine"]
projects: ["buying-intent-project/1"]
type: Bug
body:
  - type: textarea
    attributes:
      label: Current behaviour
      description: Describe the current behaviour
    validations:
      required: true
  - type: textarea
    attributes:
      label: Desired behaviour
      description: Describe the desired behaviour
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Explain how to reproduce the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: A proposed solution, preferably with example code, to showcase requested feature.
    validations:
      required: false
